version: '3'
services:
  app:
    build: .
    image: mindfort
    ports:
      - "8089:5000"
    volumes:
      - ./database:/python-docker/database
      - ./templates:/python-docker/templates
      - ./static:/python-docker/static
      - ./app.py:/python-docker/app.py
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
